language: python
sudo: required

services:
- docker

before_install:
- docker pull f5devcentral/containthedocs:latest

install: 
- pip install awscli --upgrade

script:
- ./scripts/docker-docs.sh ./scripts/test-docs.sh

deploy:
# DEPLOY TO STAGING
- provider: s3
  skip_cleanup: true
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  bucket: $AWS_S3_STAGE_BUCKET
  local_dir: docs/_build/html
  upload_dir: $AWS_DIR
  on:
    branch: staging
    repo: F5Networks/f5-aci-servicecenter

# DEPLOY TO PRODUCTION
- provider: s3
  skip_cleanup: true
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  bucket: $AWS_S3_PROD_BUCKET
  local_dir: docs/_build/html
  upload_dir: $AWS_DIR
  on:
    branch: test-kinch
    repo: F5Networks/f5-aci-servicecenter
after_deploy:
  - aws cloudfront create-invalidation --distribution-id $AWS_DIST_ID --paths $AWS_DIR
