sudo: required

language: python


services:
  - docker

stages:
  - name: build_deploy_docs


before_install:
  - docker pull f5devcentral/containthedocs:latest
  - git config --global user.email "a.kashcheev@f5.com"
  - git config --global user.name "Travis F5 ACI Service Center"


install:
  - travis_retry pip install awscli --upgrade



jobs:
  include:
    - stage: build_deploy_docs
      skip_cleanup: true
      name: build_docs_site
      script:
        - make docker-test && make docker-html
      deploy:
        skip_cleanup: true
        provider: s3
        access_key_id: $AWS_ACCESS_KEY_ID
        secret_access_key: $AWS_SECRET_ACCESS_KEY
        bucket: ak-poc-clouddocs-ci
        local_dir: docs/_build/html
        upload_dir: travis-ci-site