sudo: required

language: python


services:
  - docker

stages:
  - name: build_docs
    if: branch = draft
  - name: stage_deploy
    if: branch = staging
  - name: prod_deploy
    if: branch = master


before_install:
  - docker pull f5devcentral/containthedocs:1.0.8


install:
  - travis_retry pip install awscli --upgrade


jobs:
  include:
    - stage: build_docs
      skip_cleanup: true
      name: build_docs_site
      script:
        - chmod -R 755 script
        - make docker-html
      deploy:
        skip_cleanup: true
        provider: s3
        access_key_id: $AWS_ACCESS_KEY_ID
        secret_access_key: $AWS_SECRET_ACCESS_KEY
        bucket: $AWS_S3_TEST_BUCKET
        local_dir: docs/_build/html
        upload_dir: f5-aci-servicecenter/latest
        on:
          branch: draft
    - stage: stage_deploy
      skip_cleanup: true
      name: deploy_to_stage
      script:
        - echo "Building docs sites"
        - chmod -R 755 script
        - make docker-html
        - echo "Done with buildng docs site. Starting stagging deploy"
      deploy:
        skip_cleanup: true
        provider: s3
        access_key_id: $AWS_ACCESS_KEY_ID
        secret_access_key: $AWS_SECRET_ACCESS_KEY
        bucket: $AWS_S3_STAGE_BUCKET
        local_dir: docs/_build/html
        upload_dir: f5-aci-servicecenter/latest
        on:
          branch: staging
    - stage: prod_deploy
      skip_cleanup: true
      name: deploy_to_prod
      script:
        - echo "Building docs sites"
        - chmod -R 755 script
        - make docker-html
        - echo "Done with buildng docs site. Starting stagging deploy"
      deploy:
        skip_cleanup: true
        provider: s3
        access_key_id: $AWS_ACCESS_KEY_ID
        secret_access_key: $AWS_SECRET_ACCESS_KEY
        bucket: $AWS_S3_PROD_BUCKET
        local_dir: docs/_build/html
        upload_dir: f5-aci-servicecenter/latest
        on:
          branch: master
